lesson-12
etozhecyber/otus-go pull request #14
Opened 2020-03-24 21:39 UTC by etozhecyber

2020-04-01 16:20 UTC, Harzu requested changes

2020-04-01 16:20 UTC, kemokempo commented on calsrv/internal/adapters/psql/psql.go
> +type EventStorage struct {
Лучшим вариантом будет назвать эту структуру либо просто Storage, либо если в дальнейшем будет не одна база а несколько тогда PostgresStorage, а так же для свойства db по моему мнению больше подходит имя **client** так как в данной ситуации мы привязали коннект базы к сущности а значит и при появлении новой сущности не эвента будет новая структура стораджа, что является дублированием кода.

```go
type PostgresStorage struct {
  client *sql.DB
}
```

2020-04-01 16:20 UTC, kemokempo commented on calsrv/internal/adapters/psql/psql.go
> +		return &EventStorage{}, err
В данном случае, так как возвращаемое значение является сылкой на структуру а не самой структурой, то более правильным вариантом будет вернуть нулевой указатель **nil** нежели сылку на пустую структуру.

2020-04-01 16:20 UTC, kemokempo commented on calsrv/internal/adapters/psql/psql.go
> +func (e *EventStorage) AddEvent(ctx context.Context, event models.Event) error {
Хорошим вариантом будет отделить  методы, которые связанны с сущностью и вынести их в отдельный пакет, обычно такой пакет называется **repositories** и в нем происходят все операции взаимодействия сущностей в базу (Create Read Update Delete), а здесь лучше оставить только саму структуру клиента базы PostgresStorage и его инициализацию

2020-04-01 16:20 UTC, kemokempo commented on calsrv/internal/adapters/psql/psql.go
> +		return err
Обычно ошибки из клиента не очень информативные они будут кричать что например не удалось вытащить строки или ещё что нибудь очень общее и никакой информации о том например из какого метода была ошибка. если обработка ошибок не завязана на паниках после каждой ошибки тогда на мой взгляд лучше немного дописывать ошибки

```go
if err != nil {
  return fmt.Errorf('failed add event: %w', err)
}
```

2020-04-01 16:20 UTC, kemokempo commented on calsrv/internal/adapters/psql/psql.go
> +	query := `UPDATE events
Такие громоздкие запросы из чистого sql выглядят не совсем красиво. Чаще всего в проектах прибегают к использованию библиотек, которые собирают запросы из кода и структур например в наших проектах используется https://github.com/Masterminds/squirrel Будет круто попробовать заюзать либо эту библиотеку, либу другую на выбор, но можно и оставить голый sql это тоже вариант

2020-04-01 16:20 UTC, kemokempo commented on calsrv/internal/adapters/psql/psql.go
> +		return models.Event{}, err
В данном случае нельзя отдать nil потому что мы не отдаем указатель на эвент а отдаём сам эвент поэтому здесь действительно логично отдать структуру при ошибке. Так-же для того что бы уменьшить дублирование  можно в начале создать структуру и по всей функции внизу при ошибках её и отдавать и не создовать новые структуры при каждой ошибке

```go
func aaa() (MyStruct, error) {
  result = MyStruct{}
  if err := Scan(result); err != nil {
    return result, err
  }
  return result, nil
}
```

2020-04-01 16:20 UTC, kemokempo commented on calsrv/internal/adapters/psql/psql.go
> +	query := `DELETE FROM events
Маленькие запросы можно умещать в одну строку.  Так они занимают меньше места и лучше смотрятся при чтении кода

2020-04-01 16:20 UTC, kemokempo commented on calsrv/internal/adapters/psql/psql.go
> +	for rows.Next() {
Конструкция встречается несколько раз, возможно стоит выделить её в отдельную функцию и вызывать дабы уменьшить дублирование

2020-04-01 16:20 UTC, Harzu commented on calsrv/migration/1-schema.sql
> +create user calserv with encrypted password 'password';
такие вещи как креды для базы лучше создавать вручную и прописывать либо в конфиге, либо в переменных окружения.

2020-04-03 00:07 UTC, etozhecyber commented on calsrv/internal/adapters/psql/psql.go
> +type EventStorage struct {
Переделал

2020-04-03 00:07 UTC, etozhecyber commented on calsrv/internal/adapters/psql/psql.go
> +func (e *EventStorage) AddEvent(ctx context.Context, event models.Event) error {
Отделил

2020-04-03 00:08 UTC, etozhecyber commented on calsrv/internal/adapters/psql/psql.go
> +	query := `UPDATE events
Подключил, выглядит удобно. но только на update'е. В остальных запросах излишне

2020-04-03 00:08 UTC, etozhecyber commented on calsrv/internal/adapters/psql/psql.go
> +		return models.Event{}, err
Справедливо. Я переделал

2020-04-03 00:10 UTC, etozhecyber commented on calsrv/migration/1-schema.sql
> +create user calserv with encrypted password 'password';
Я переделал. make переменную с паролем может взять как аргумент запуска и как переменную окружения и даже дефолтное значение есть

2020-04-03 00:10 UTC, etozhecyber commented on calsrv/internal/adapters/psql/psql.go
> +	for rows.Next() {
Вынес

2020-04-05 14:49 UTC, merged